spring:
  profiles: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.97.159.83:8306/nt2?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: root
    druid:
      initial-size: 3
      max-active: 10
      min-idle: 1
      max-wait: 6000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 10
      #等价于上面的max-pool-prepared-statement-per-connection-size
      max-open-prepared-statements: 10
      validation-query: select 1 from dual
      validation-query-timeout: 3000
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 6000
      max-evictable-idle-time-millis: 60000
      min-evictable-idle-time-millis: 30000
      filters: stat,wall
      web-stat-filter:
        enabled: true
        urlPattern: /*
        exclusions: /druid/*
        sessionStatMaxCount:
        sessionStatEnable: false
        principalSessionName:
        principalCookieName:
        profileEnable:
      stat-view-servlet:
        enabled: true
        urlPattern: /druid/*
        resetEnable:
        loginUsername: druid
        loginPassword: druid
        allow:
        deny: 255.255.255.255
        aop-patterns: false
mybatis-plus:
  configuration:
    call-setters-on-nulls: true
    cache-enabled: true
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1
  mapper-locations: classpath:com/example/mybatis/dao/*.xml
logging:
  home: D:/data/nt2/logs/${spring.application.name}
  level:
    com.example.mybatis: trace
